"""empty message

Revision ID: 01e78c5ded52
Revises: f7719dedf7ab
Create Date: 2020-04-16 01:18:14.316802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01e78c5ded52'
down_revision = 'f7719dedf7ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_table_firstName', table_name='order_table')
    op.drop_table('order_table')
    op.drop_index('ix_user_firstName', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user_firstName', 'user', ['firstName'], unique=False)
    op.create_table('order_table',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_order_table_firstName', 'order_table', ['firstName'], unique=False)
    # ### end Alembic commands ###
