"""empty message

Revision ID: eb2a44f1a243
Revises: 01e78c5ded52
Create Date: 2020-04-16 01:19:34.624698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2a44f1a243'
down_revision = '01e78c5ded52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('invoice_term_name', sa.String(length=32), nullable=True),
    sa.Column('invoice_date', sa.String(length=32), nullable=True),
    sa.Column('customer_account_number', sa.String(length=32), nullable=True),
    sa.Column('vendor', sa.String(length=32), nullable=True),
    sa.Column('order_items', sa.String(length=32), nullable=True),
    sa.Column('raw_sold_to_info', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('invoice_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_firstName'), 'user', ['firstName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_firstName'), table_name='user')
    op.drop_table('user')
    op.drop_table('order')
    # ### end Alembic commands ###
