"""empty message

Revision ID: edccf511592b
Revises: 8f48d118833a
Create Date: 2020-04-15 14:55:37.895445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edccf511592b'
down_revision = '8f48d118833a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_fName', table_name='user')
    op.drop_column('user', 'fName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fName', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True))
    op.create_index('ix_user_fName', 'user', ['fName'], unique=False)
    # ### end Alembic commands ###
