"""empty message

Revision ID: f7719dedf7ab
Revises: 195c7970dd49
Create Date: 2020-04-16 00:32:29.348427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7719dedf7ab'
down_revision = '195c7970dd49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_table_firstName'), 'order_table', ['firstName'], unique=False)
    op.drop_index('ix_user1_firstName', table_name='user1')
    op.drop_table('user1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user1',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(collation='utf8mb4_general_ci', length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_user1_firstName', 'user1', ['firstName'], unique=False)
    op.drop_index(op.f('ix_order_table_firstName'), table_name='order_table')
    op.drop_table('order_table')
    # ### end Alembic commands ###
